// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuMsOWlpS73wCRs9ibObTjaYLUTStDOss',
    appId: '1:373089680388:web:91a893f4be73767aedc951',
    messagingSenderId: '373089680388',
    projectId: 'eands-internship-2026',
    authDomain: 'eands-internship-2026.firebaseapp.com',
    storageBucket: 'eands-internship-2026.firebasestorage.app',
    measurementId: 'G-K7PMKB7WWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD75tSoNV2HS9aw1SGnfFJx8LzprEPxFH0',
    appId: '1:373089680388:android:265b9a0086f57470edc951',
    messagingSenderId: '373089680388',
    projectId: 'eands-internship-2026',
    storageBucket: 'eands-internship-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxRo-H1CJ8VOYpEMJtVlxl3Gf4-vo7nM',
    appId: '1:373089680388:ios:9cd75f839db85682edc951',
    messagingSenderId: '373089680388',
    projectId: 'eands-internship-2026',
    storageBucket: 'eands-internship-2026.firebasestorage.app',
    iosBundleId: 'com.example.eandsinternship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxRo-H1CJ8VOYpEMJtVlxl3Gf4-vo7nM',
    appId: '1:373089680388:ios:9cd75f839db85682edc951',
    messagingSenderId: '373089680388',
    projectId: 'eands-internship-2026',
    storageBucket: 'eands-internship-2026.firebasestorage.app',
    iosBundleId: 'com.example.eandsinternship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuMsOWlpS73wCRs9ibObTjaYLUTStDOss',
    appId: '1:373089680388:web:4198f2d28f1aa335edc951',
    messagingSenderId: '373089680388',
    projectId: 'eands-internship-2026',
    authDomain: 'eands-internship-2026.firebaseapp.com',
    storageBucket: 'eands-internship-2026.firebasestorage.app',
    measurementId: 'G-STQB7GXJ84',
  );
}
